# Generated by Django 3.1.3 on 2021-11-28 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavouriteCourse',
        ),
    ]
