# Generated by Django 3.1.3 on 2021-11-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_classroomstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomstudents',
            name='classroom',
        ),
        migrations.AddField(
            model_name='classroomstudents',
            name='classroomname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
